<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="55" started-at="2016-04-26T07:58:02Z" finished-at="2016-04-26T07:58:02Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="55" started-at="2016-04-26T07:58:02Z" finished-at="2016-04-26T07:58:02Z">
      <class name="com.qishon.isw.apitest.GetCartListTest">
        <test-method status="FAIL" signature="getDestnationTest(java.lang.String, java.lang.String)[pri:0, instance:com.qishon.isw.apitest.GetCartListTest@7c4c98e7]" name="getDestnationTest" duration-ms="33" started-at="2016-04-26T15:58:02Z" data-provider="testdata1" finished-at="2016-04-26T15:58:02Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[SP_MAS_GETCARTLIST]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[200]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Data value must not be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Data value must not be null
	at org.jsoup.helper.Validate.notNull(Validate.java:26)
	at org.jsoup.helper.HttpConnection$KeyVal.value(HttpConnection.java:891)
	at org.jsoup.helper.HttpConnection$KeyVal.create(HttpConnection.java:871)
	at org.jsoup.helper.HttpConnection.data(HttpConnection.java:131)
	at com.qishon.isw.api.GetCartList.getCartList(GetCartList.java:37)
	at com.qishon.isw.apitest.GetCartListTest.getDestnationTest(GetCartListTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getDestnationTest -->
      </class> <!-- com.qishon.isw.apitest.GetCartListTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
